feat : ensure config works correctly

diff --git a/frontend/Dockerfile b/frontend/Dockerfile
--- a/frontend/Dockerfile
+++ b/frontend/Dockerfile
@@ -2,7 +2,7 @@
 #--------------------------------------------
 # Dev Stage - Assembles and Builds Frontend
 #--------------------------------------------
-FROM --platform=$BUILDPLATFORM node:18-alpine as dev
+FROM --platform=$BUILDPLATFORM node:20-alpine AS dev
 
 ARG APP_SHELL_VERSION=next
 
@@ -13,9 +13,17 @@ COPY spa-assemble-config.json .
 COPY spa-build-config.json .
 
 ARG CACHE_BUST
-RUN npx --legacy-peer-deps openmrs@${APP_SHELL_VERSION:-next} assemble --manifest --mode config --config spa-assemble-config.json --target ./spa
-RUN npx --legacy-peer-deps openmrs@${APP_SHELL_VERSION:-next} build --build-config spa-build-config.json --target ./spa
-RUN if [ ! -f ./spa/index.html ]; then echo 'Build failed. Please check the logs above for details. This may have happened because of an update to a library that OpenMRS depends on.'; exit 1; fi
+RUN npx --legacy-peer-deps openmrs@${APP_SHELL_VERSION:-next} \
+    assemble --manifest --mode config \
+    --config spa-assemble-config.json \
+    --target ./spa
+RUN npx --legacy-peer-deps openmrs@${APP_SHELL_VERSION:-next} \
+    build --build-config spa-build-config.json \
+    --target ./spa
+RUN if [ ! -f ./spa/index.html ]; then \
+    echo 'Build failed. Please check the logs above for details. This may have happened because of an update to a library that OpenMRS depends on.'; \
+    exit 1; \
+    fi
 
 #--------------------------------------------
 # Runtime Stage - Published Image
@@ -27,15 +35,19 @@ RUN apk update && \
     # add more utils for sponge and envsubst
     apk add --no-cache moreutils
 
-# clear any default files installed by nginx
-RUN rm -rf /usr/share/nginx/html/*
+# Create directory for SPA files
+RUN mkdir -p /usr/share/nginx/html
 
 COPY startup.sh /usr/local/bin/startup.sh
 RUN chmod +x /usr/local/bin/startup.sh
 
 COPY nginx.conf /etc/nginx/nginx.conf
 
-COPY --from=dev /app/spa /usr/share/nginx/html
-COPY config-core_demo.json /usr/share/nginx/html
+# Copy SPA files to a temporary location
+COPY --from=dev /app/spa /tmp/spa
 
-CMD ["/usr/local/bin/startup.sh"]
+# Mount point for SPA config files
+VOLUME ["/usr/share/nginx/html"]
+
+# Copy SPA files after volume mount
+CMD ["/bin/sh", "-c", "cp -R /tmp/spa/* /usr/share/nginx/html/ && /usr/local/bin/startup.sh"]
